### PR TITLE
Rapid api Component

### PR DESCRIPTION
**Pull request by caroline223**
Description:

Milestone 2 completion: tooltip and toggle completed with appropriate user settings captured for both interactions (tooltip and map).

### CODE REVIEW

**Comment by jschwarz2030** [comment]
Screenshot 2023-03-31 at 9 06 18 PM

when running `yarn build` i run into the above error.

Screenshot 2023-03-31 at 9 07 18 PM

When toggling on "Edit Mode", the site crashes

**Review by MattEspoz — COMMENTED** [review]
updates on the fixes: now records previous user settings.

**Comment by jschwarz2030** [comment]
Screenshot 2023-04-04 at 8 16 27 AM

what are these files for?

**Comment by jschwarz2030** [comment]
Screenshot 2023-04-04 at 2 50 51 PM

Why are there suddenly duplicate files all over the place?

**Comment by jschwarz2030** [comment]
Screenshot 2023-04-04 at 2 52 17 PM

and i still don't understand what these files are for

**Comment by MattEspoz** [comment]
That's really wierd. I'll look into why it duplicated the files right away. And I have no idea what the .icloud files are, I think they might be autogenerate cache or something

Sent via Superhuman ( ***@***.*** )

**Comment by MattEspoz** [comment]
Ok I just cleared all of them. Only the relevant files are left

**Comment by jschwarz2030** [comment]
closing.  will re-establish Rapid integration in a fresh branch and PR

**Pull request closed without merging**
