### PR TITLE
change button "Too Hard / Can't See" to "Can't Complete"

### PR DESCRIPTION
**Pull request by CollinBeczak**
Resolves MR3 fix for issue: https://github.com/maproulette/maproulette3/issues/1779

### CODE REVIEW

**Comment by govvin** [comment]
The confirmation dialog still shows "Too hard" reference from the old labels
image

And the shortcut key legend doesn't show a "Can't See" shortcut bud "d" is still bound to "too difficult/couldn't see".
image

**Comment by jschwarz2030** [comment]
Are we wanting the shortcut key changed from 'd' to something else?

**Comment by jschwarz2030** [comment]
what shortcut key do you want it to be

**Comment by govvin** [comment]
I personally use the shortcut keys a lot, and I thought some of the current ones aren't very mnemonic

For example, with current shortcut "b" for "complete tasks together" , I think of "(b)atch" and the letter "b" is not even in the label in the phrase "complete tasks together". 

Harder to remember, right?   I think  "batch" is no longer a familiar  term, so maybe consider "(b)undle tasks for completion" label rather than "complete tasks together" so users can easily associate shortcut keys with the action better?

Other random thoughts: 
key | current assignment | candidate action | notes
--- | --- | --- | ---
x | already fixed | can't be fixed | "x" like a close button action for a window
s | toggle feature layer | skip | skip starts with "s"
w | skip | | maybe "n" like (n)ext
a || already fixed | (a)lready fixed
t || toggle feature layer | (t)oggle feature layer

I haven't checked, but above may conflict with existing shortcut keys.

**Pull request merged**
